### ISSUE TITLE
[Bug] Broken AMOLED mode

### ISSUE THREAD

**Issue by Henry-Hiles** [Aliucord/AliucordRN#39] opened 2022-11-08 16:48 UTC
At first when you turn on AMOLED mode in AliucordRN, everything works as expected. However, after a restart, only some elements have AMOLED applied.

**Comment by Austcool-Walker** [comment] 2022-11-26 17:21
> At first when you turn on AMOLED mode in AliucordRN, everything works as expected. However, after a restart, only some elements have AMOLED applied.

I can confirm this is a error for me as well.

**Comment by NightNutSky** [comment] 2022-12-19 22:51
Yeah

**Comment by MatadorProBr** [comment] 2023-01-02 16:38
Probably this issue could be closed now since it's fixed?

**Comment by rushiiMachine** [comment] 2023-01-02 16:41
Fixed by #42

**Closed by rushiiMachine** 2023-01-02 16:41 UTC
